### ISSUE TITLE
Translation blocked

### ISSUE THREAD

**Issue by josuigoa** [beat-feet/beat-feet#139]
Hi!

I would like to translate the game to Basque. I've added the language in weblate and could translate App Metadata and the Glossary, but weblate is showing me a tip when trying to click the + button that says "Cannot add a translation now".

Do I have to do something else?

**Comment by pserwylo** [comment]
Thank you so much for your contribution @josuigoa - I am always exceptionally grateful to the community of translators who contribute to little apps like this.

I turned some settings on the GitHub side which stuffed this up (specifically - I said that each change needs a PR, and the PR needs to wait for the CI build to be successful - this stopped weblate working). I've reverted that and told Weblate that it can push now. Hopefully you are now able to add a translation. Please ping back here if you are not.

Once added, it will still take me a few days to get around to manually adding it. Essentially I need to ensure that the fonts used contain the right glyphs for each new language, and then manually enable that language in the game code. Otherwise, the game will just start showing blank text to users of your language.
