### ISSUE TITLE
Add info for new users

### ISSUE THREAD

**Issue by Glitchy-Tozier** [beat-feet/beat-feet#63]
Just add a `introduction`-button to the menu or a `(?)` to the top-right/left of the screen. When clicked on, it should mention some basic principles of the game in a consise way.

Stuff like this:
- Jump by tapping on the screen
- You may double-jump by tapping a second time
- Running into buildungs damages you
- Running into posts damages you
- The more you jump and the longer you refrain from touching the ground, the more points you get

For example, when playing the game for the first time, it took me a few minutes to realize that the posts could (and did) actually hurt me. It took me even longer to understand how points work.

**Comment by Glitchy-Tozier** [comment]
Also display this when starting a level **if this is the first time the user plays a level any level**.

(Meaning only show this once, not for every level)

**Comment by pserwylo** [comment]
This is a good point.

On the one hand, it is only fair to offer an explanation of rules and mechanics to new players.

On the other hand, I **love** that first time gamers can pick up Super Mario Brothers on the NES and just start playing. I've strived to make this game such that no education is necessary, and I'm pleased that the dot points you've put above are essentially the entire rules of the game, and you have deduced them very accurately. I've also gotten two pieces of feedback from play testers in my family who both love the chaos that ensued the first time you start playing and just mashing the screen, until you kind of find your grove and figure it out.

How about: Check out the v0.3.0 build (either debug build via GitHub or when F-Droid builds and releases it soon). That has the Laundry Room as the first level, which is quite straightforward and hopefully doesn't induce a lot of panic when playing. If people still feel there is a strong need for instructions after being introduced via that level, then we can put it in the "About" page above the "Credits" (e.g. "How to Play").

**Comment by Glitchy-Tozier** [comment]
Understood. I agree that those games are great and if you want to make that kind of game, go for it!  :)

In that case though, consistency and giving clear indicators is really important. Some things I can think of are:
- #37
- #66
- #67

**Comment by pserwylo** [comment]
Thanks. I agree with those other tickets regarding visual feedback. Now that we have [shields coming in v0.4.0](https://github.com/beat-game/beat-game/issues/59#issuecomment-791148597), I'd really like to show something like the following:

![image](https://user-images.githubusercontent.com/248565/110068689-5520a280-7dca-11eb-9614-65a962e0ce53.png)

For when you get hit by a shield (in addition to the shields themselves shown below the hearts breaking apart), and something similar for no-shield (i.e. red particles instead, without the shield image).

**Comment by Glitchy-Tozier** [comment]
Soznds good too!  :)

**Comment by pserwylo** [comment]
I want itto he hard! So if it turns out too easy, I'll just lesser the impact of the shield.

It als ooccurs to me that a great long-term plan is to start with a capacity of 2 hearts and no shield, then the player earn perks by spending diamonds (earnt from high scores). Buying them are permanent perks that stay with you. 

Things that immediately come to mind:
* Buy heart capacity (e.g. like in Zelda)
* Buy shield capacity
* Buy strength (to reduce the damage taken, regardless of shield)

Some more iffy thoughts:
* Buy the ability to jump higher. 
* Start with a single jump and buy the double jump ability. 

The reason I bring this up here is because it would start extremely hard, and you would really need to slog and then upgrade to get to a point where it *is* in fact easy, even with shield mechanics, etc.

**Comment by pserwylo** [comment]
P.S. would you like to be made a "reporter" in this repo/organisation? I really appreciate your well thought out commentary, and the way you articulate not just the problem you are facing, but also specify well thought out potential solutions and engage in discussion.

 No strings attached, you could just have the ability to close and edit issues and discussions. Also I won't be offended if you say "thanks but no thanks".

**Comment by Glitchy-Tozier** [comment]
> Would you like to be made a "reporter" in this repo/organisation?

I really appreciate the offer, but I think I'll leave all the editing-privileges with you  :)
Thank you though, I feel honored.

> I want it to he hard! So if it turns out too easy, I'll just lesser the impact of the shield.

> Things that immediately come to mind:
•    Buy heart capacity (e.g. like in Zelda)
•    Buy shield capacity
•    Buy strength (to reduce the damage taken, regardless of shield)
Some more iffy thoughts:
•    Buy the ability to jump higher.
•    Start with a single jump and buy the double jump ability.

I guess it's a file line between giving the user new options and making it easier to the user. If you want to hear my opinion:
- If the game is pretty much unbeatable in the beginning, then those "power-ups" you mentioned sound good.
(comparable to Zelda, where you pretty much need the bomb-bag or a better armor or a bottle in order to progress through the game.)
- If the game *can* be beaten without any power-ups (like most Mario games or Geometry Dash), you should be careful about introducing those power-ups.
Think about a Mario game where Mario can get a free star every 15 seconds and only takes half the damage and has 4 "downgrades" before he dies. That wouldn't be a very exciting Mario game.
(Of course that was a very extreme example)

All in all, I think it's up to what kind of game you want it to be. If power-ups are a core part of the game, add them. If it's a game where all that is required is practice&skill, you shouldn't add something that might make this aspect of the game less important.

> Buy the ability to jump higher.

Also, if you were to add that, it would need a lot of testing. I'm a little concerned it might mess up people's muscle memory.

**Comment by xloem** [comment]
Regarding new users:  on my phone the level does not appear to be related to the beats in any way I understand.  On some games, you move in time with the music.  I'm not sure whether that is the intention here or not, to know whether there is a bug on my device or not.

**Comment by Glitchy-Tozier** [comment]
Jup, the use definitely doesn't "feel" the music in the stages.

**Comment by comradekingu** [comment]
I love how there is no intro or difficulty setting. It feels like discovering a genuine game.
My unpopular opinion is that hand-holding and tutorials ruined discovery, mastery and overcoming challenges.

I am old. Remember helicopter and moonlander on C64/Amiga, difficulty on asian"-old. As a kid I could accept that, and yes I haven't accepted a lot of nonsense since. It doesn't have to be my way, but then again I don't have to be like everyone else.

Arriving in the "game" immersion, is thus my own mind. There is no need to sell me on the game, or steal my data. I want to try to have fun, rather than consider a bunch of info, and whether that will be a good experience or not.

Always catching a fish is not fishing.
If I am told how to play, that isn't play. In the game world (or generally) I am not afraid to die, I want to keep my guy alive. I like the graphics, I am emotionally invested in his world and endeavours. That is a sacrifice I will make with every bit of determination. I will do my best even if I know death looms around the corner, especially if that is inevitable given my skillset. There is a humility to it.

This is one of the positive aspects of playing games. Increased hand-eye coordination, etc. Deactivating gray-matter is also a possible result.

As I have gotten older I realize someone is making these games. There is a subtle communication going on between me and the person that enjoys my culture. The demo-scene of the 90s was indeed that.

I play games to think about something else. Triggering some ingenuity takes my mind away.
I don't want to be in the queue for the ride.

It is easy to consider the unpleasantness of not understanding or dying as something that can be done away with to increase enjoyment of the game. What it actually does is make things generic, characterless, dull. Play stupid games, lose out on playing good games.

The important part about facing difficulty is that it doesn't make you stop playing the game. You overcome. Thereby going back without it actually changes the premise of the joy you have once acquainted.

Psychologically, this is a positive feedback loop that increases testosterone. The level of difficulty that is too high is where you get your attempts handed to you in a manner that just tells you the game isn't for you at all.

If everyone plays the same game, there is more of a understood challenge. Just moving the selector to "easy" ruins that.
Menus in games are not why people play them.

How about instead of the usual pay-to-win, I offer up funds to the contrary? Pay-to-suffer :)
Got plenty ideas for interesting things to keep what initially works fresh and exciting.

**Comment by pserwylo** [comment]
I'm going to close this now, thanks for all of your feedback. The latest version in F-Droid just says "Tap to jump" at the start of each level, which fades away after a second or so. This feels like about the right level of instruction to me, but happy to hear any other feedback.

**Comment by xloem** [comment]
What would clear it up is a line somewhere like, "this is intended to be a beat game but we need help with the signals analysis, so it's just a jumping game for now"

**Comment by pserwylo** [comment]
@xloem - not a problem, just happy you took the time to come and be involved in the discussion :)

**Comment by comradekingu** [comment]
I don't get the joke.
Games can be magical. Explanation instead of exploration is decidedly not.

It would be fun if there was some deeper meaning administered in the form of writing, every now and then when the game is started.

**Comment by xloem** [comment]
"Once upon a time, in a video game far far away, researchers discovered that computers could analyse music ..."

**Comment by xloem** [comment]
"Once upon a time, in a video game far far away, researchers discovered that computers could analyse music ..."

**Comment by xloem** [comment]
"Once upon a time, in a video game far far away, researchers discovered that computers could analyse music ..."

**Comment by xloem** [comment]
"Once upon a time, in a video game far far away, researchers discovered that computers could analyse music ..."
