### ISSUE TITLE
Text overflows screen

### ISSUE THREAD

**Issue by omichaelo** [beat-feet/beat-feet#77]
On some screens, the text overflows the screen. See picture. 
Also, what's the directory to put custom songs? I can't figure it out because the directory text overflows and is cut off. 
![Screenshot_20210324-215453_beat-game](https://user-images.githubusercontent.com/14541847/112421190-d98c8400-8ceb-11eb-91e8-8ca6c7903ca1.png)

**Comment by pserwylo** [comment]
Haha, whoops! Thanks for the bug report (especially including the screenshot). I think I'll try to:
* Make the font smaller for that part
* Add a small button below (same height as the "Back" button on this screen), which says "Open custom folder". When clicked, it will prompt you to open the folder in your file browser of choice.

In the meantime, the location you seek depends on your device. On mine, it is: `/sdcard/Android/data/com.serwylo.beatgame/files/BeatChange/`.

By the look of it, yours is likely to be: `/emulated/0/Android/data/com.serwylo.beatgame/files/BeatChange`.

**Note:** the folder "BeatChange" was from before when it was a working title. I will rename this soon, but the application will tell you if it changes (by prompting you to put a file elsewhere, e.g. in a subdirectory called "CustomMP3s" or something... whatever it is it will be in the UI).

**Comment by pserwylo** [comment]
Alright, this has now been fixed in the current `master` branch. I will tag a release to be built by F-Droid after a few days in case there is any translations for the changelog. This will be my process going forward now that the game can be translated. Normally no more than a week between bug fixing and then tagging (plus time required for F-Droid to pick up the tag, build, and release).

Thanks again for your contributions!
