### ISSUE TITLE
Translation for other languages

### ISSUE THREAD

**Issue by comradekingu** [beat-feet/beat-feet#87]
Would be nice to see this game on Weblate in some capacity.
Either https://hosted.weblate.org/hosting/ or another platform.

Happy to help set it up, I am https://hosted.weblate.org/user/kingu/ on there, and similar other places.

**Comment by pserwylo** [comment]
100%. This is actually almost ready to go - you've read my mind ;)

I even recently extracted all of the strings in preparation for this: https://github.com/beat-feet/beat-feet/commit/4bd0db288d97847dd7acad1b2667ab14dcc80332#diff-4cef5d55041b0b34d3403472d9a8d5462c77ca99e387146d4178401f6d43e8d5.

So yes, I will ask Weblate for a Libre account there in the coming days.

Also, I may as well thank you here for all your language contributions to many open source projects - I've seen you contributing to F-Droid, Lexica, and Baby Dots through the years, and I'm sure others in the community appreciate your contributions too. Keep it up!

**Comment by pserwylo** [comment]
Hi @comradekingu - I've added to Weblate now. Would love to see if you are able to translate accordingly. All my other apps have a pretty straightforward Android strings.xml structure. Because this used the libgdx library, it has a different way of internationalising (by using Java *.properties files). I think I've set it up appropriately, but if you are able to translate then I will double check all is well and then push a new release.

**Comment by comradekingu** [comment]
@pserwylo
Worked fine for the metadata files, the app strings are currently locked.

**Comment by pserwylo** [comment]
Wow, thanks for the super quick response. Turns out I configured permissions on GitHub incorrectly for Weblate, and it locks by default when a repository cannot be pushed to. This is now resolved and the app strings should now be unlocked.

**Comment by pserwylo** [comment]
Thanks again for the updated translations. This helped unearth a separate issue which is now addressed. Specifically, the language files created by Weblate used `-` by default, resulting in `messages_nb-NO.properties` being created, instead of `messages_nb_NO.properties` required by libgdx. Turns out there is (as always) a perfect setting added by the Weblate team to deal with this. For anyone else curious, go to the component in question (Game Strings for this project), settings, files, then "Language Code Style". Then change from "Default based on the file format" to "POSIX style using underscore as a separator".

![image](https://user-images.githubusercontent.com/248565/113495575-1a7b6880-9536-11eb-905a-02e31ad60683.png)

Now we should be up and running for future translations (you can see me experimenting with `pt_PT` in the commit log). I'll prepare a new release soon so that we can broadcast to others via "Whats New" in F-Droid that translations are now supported.

**Comment by pserwylo** [comment]
Looking good:

![image](https://user-images.githubusercontent.com/248565/113499991-e5830c00-955d-11eb-9eaf-b731a9c0edbf.png)
