### ISSUE TITLE
Vibrating hearts go out of screen

### ISSUE THREAD

**Issue by bydariogamer** [beat-feet/beat-feet#89]
If you get little life and keep playing for long time the hearts that represent lives start going up and end going out of screen (it takes some time, but happens). It might be caused by some float that then are turned into int over and over, but I have no idea on how does your code work 😅 .

**Comment by pserwylo** [comment]
Thanks for the report @bydariogamer - apologies for taking so long to get back to you - but the fix will be in the next release.

If you're interested, I was accidentally moving *vertically up* by `0.03` *pixels* each shake, instead of moving *horizontally* for `0.03` *seconds*.

As an added bonus, the fix makes it shake in a slightly smoother and nicer way.
